### PR TITLE
Feature/enable restart with snackbar

### LINKED ISSUE #67: Avoid closing app to restart node and apply new settings
One possibility is to detect that settings changed and display a dialog which asks the user if he wants to restart the node/app.

### PR DESCRIPTION
**Pull request by PerrineAguiar**
This PR adds a snackbar to allow the user to restart the running activity if the ros master settings changed.

screenshot_2017-01-12-17-29-26

Fixes #67.

### CODE REVIEW

**Comment by smits** [comment]
Can we move forward on this one?  Would be nice to have it in.

**Comment by PerrineAguiar** [comment]
@smits Can we close this?
With #275 we don't need to restart the app if ros connection failed. A snackbar appears with the reconnect button in the RunningActivity instead.

Note: You still need to restart the app if you change the ros master settings while the nodes are running, but that seems ok, it is the same behavior when running a node on linux.

**Comment by smits** [comment]
I would prefer a possibility to reconnect to a master without having to restart the app, but I understand that it might be hard to accomplish.

**Comment by PerrineAguiar** [comment]
Ok, I will take a closer look at it when tackling #82.

**Pull request closed without merging**
